### Refresh user token
POST {{host}}/api/users/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsInVzZXJpZCI6IjNjOGYyMDc2LWNkYjItNDE2Ny05ZGJmLTlhOTVmYTA0YTA5YiIsInJvbGUiOiJBZG1pbiIsImp0aSI6IjU5MGYwYzY4LWQ3NWYtNDgxOS05ODBjLTkzNjhkMzUxOTNkOCIsInVzZXJzOnJlYWQiOiJ0cnVlIiwidXNlcnM6Y3JlYXRlIjoidHJ1ZSIsInVzZXJzOnVwZGF0ZSI6InRydWUiLCJ1c2VyczpkZWxldGUiOiJ0cnVlIiwic2hpcG1lbnRzOnJlYWQiOiJ0cnVlIiwic2hpcG1lbnRzOmNyZWF0ZSI6InRydWUiLCJzaGlwbWVudHM6dXBkYXRlIjoidHJ1ZSIsInNoaXBtZW50czpkZWxldGUiOiJ0cnVlIiwiY2FycmllcnM6cmVhZCI6InRydWUiLCJjYXJyaWVyczpjcmVhdGUiOiJ0cnVlIiwiY2FycmllcnM6dXBkYXRlIjoidHJ1ZSIsImNhcnJpZXJzOmRlbGV0ZSI6InRydWUiLCJzdG9ja3M6cmVhZCI6InRydWUiLCJzdG9ja3M6Y3JlYXRlIjoidHJ1ZSIsInN0b2Nrczp1cGRhdGUiOiJ0cnVlIiwic3RvY2tzOmRlbGV0ZSI6InRydWUiLCJleHAiOjE3NTM2MjQ4NzksImlzcyI6IkRldlRpcHMiLCJhdWQiOiJEZXZUaXBzIn0.OVH3WtLHFcn-H6o7xTNDH0HtIs_gKmhcsj1Wt2K6Kd4",
  "refreshToken": "2d6b65a9-cf24-4026-aa2f-30d016ede76e"
}